### ISSUE TITLE
Issues about data preprocessing

### ISSUE THREAD

**Issue by Vicky-51** [tsy935/eeg-gnn-ssl#3]
Great work!

I'm trying to reproduce this excellent work. I get some trouble during data preprocessing. For the data resampling, I have the following error:

ValueError: 'EEG FZ' is not in list.

Could you please provide some suggestions about this?

Thank you!

**Comment by tsy935** [comment]
Hi, thank you for your interest!

Looks like some patients are missing the channel "EEG FZ" in the newer versions of TUH data. I've updated `resample_signals`, where failed files will be skipped: https://github.com/tsy935/eeg-gnn-ssl/blob/main/data/resample_signals.py#L29-L50

You can choose to exclude these EEGs without the complete list of 19 EEG channels in your experiments.

**Comment by Sample-design-alt** [comment]
It looks like there are some new problem in the newer versions.  
In the training process, it would be raise error like this:
![image](https://user-images.githubusercontent.com/66257621/188468533-62db9644-767c-4a45-9887-88e5ea556944.png)

**Comment by PhoebeLiu0109** [comment]
> It looks like there are some new problem in the newer versions. In the training process, it would be raise error like this: ![image](https://user-images.githubusercontent.com/66257621/188468533-62db9644-767c-4a45-9887-88e5ea556944.png)

I‘m having the same problem:( How did you solve that anyway?
